name = "tripcrafti"
pages_build_output_dir = "dist"
compatibility_date = "2025-02-04"

[vars]
PUBLIC_SUPABASE_URL = "https://cyusoliinkrsrtxgtbbl.supabase.co"
PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5dXNvbGlpbmtyc3J0eGd0YmJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNTEzNDAsImV4cCI6MjA3NDcyNzM0MH0.rQUT-Em7pzomm0l4JDZbGWcsYk6vfZUL3Xs2NJfmXuM"
PUBLIC_FX_API_BASE = "https://api.exchangerate.host"
DEBUG_LOGGING = "false"

[[kv_namespaces]]
binding = "SECRETS" # KV namespace for runtime secrets (GEMINI_API_KEY, UNSPLASH_ACCESS_KEY, etc.)
id = "b2c9e78506a7423ba7d15b7bef93d7e4"

[secrets]
UNSPLASH_ACCESS_KEY
GEMINI_API_KEY
EXCHANGERATE_API_KEY
GOOGLE_GEOCODING_API_KEY
TICKETMASTER_API_KEY